### ISSUE TITLE
本项目可以用于Hi2821 BS21芯片板吗？

### ISSUE THREAD

**Issue by Burial0268** [geekheart/burntool#1]
RT.
之前我使用 goodspeed34/ws63flash 这个项目来烧写 BS21 Hi2821 开发板。现由于生产环境的原因欲切换至本项目，想知道对该型号的烧写可行性

**Comment by geekheart** [comment]
可以的哦，我自己试过，没问题

**Comment by Burial0268** [comment]
抱歉现在才看到🙏 非常感谢作者能回复，已经使用着了，感谢开源
